import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      nav: { home: "Home", features: "Features", howItWorks: "How It Works", dashboard: "Dashboard", appointments: "Appointments", ocrScanner: "OCR Scanner", contact: "Contact", logout: "Logout", hi: "Hi" },
      hero: { badge: "Live Health Monitoring", title1: "HealthSync", title2: "Smart Healthcare,", title3: "Seamlessly Connected", subtitle: "Monitor vitals in real-time, get instant AI health insights, and stay connected with your healthcare team — anytime, anywhere.", startBtn: "Start Monitoring", aiBtn: "Talk to AI Assistant", ocrBtn: "OCR Scan", feat1Title: "Real-time Monitoring", feat1Desc: "Continuous Temperature, SpO₂, and Humidity monitoring with IoT-grade reliability and millisecond latency.", feat2Title: "AI Insights", feat2Desc: "Advanced predictive analytics powered by CNN, LSTM, and Transformer models for early risk detection.", feat3Title: "Secure Dashboard", feat3Desc: "Cloud-synced health history, encrypted storage, and comprehensive alerts for complete peace of mind.", stat1: "Uptime", stat2: "Monitoring", stat3: "Predictions", stat4: "Cloud Storage" },
      home: { core: "Core Features", why: "Why Choose HealthSync?", whyDesc: "Experience the future of healthcare with our cutting-edge technology that puts your health monitoring in your hands.", moreFeat: "More Powerful Features", moreFeatDesc: "Discover additional capabilities that make HealthSync the complete health monitoring solution.", ctaTitle: "Ready to Transform Your Health Monitoring?", ctaDesc: "Join thousands of users who trust HealthSync for their health monitoring needs.", ctaBtn1: "Get Started Now", ctaBtn2: "Learn More", f1_title: "Real-time Vitals", f1_desc: "Continuous Temperature, Oxygen, and Humidity monitoring with IoT-grade reliability and instant health insights.", f2_title: "Predictive AI", f2_desc: "Advanced CNN, LSTM, and Transformer models that estimate risk and trends early, providing proactive health management.", f3_title: "Secure Cloud", f3_desc: "Enterprise-grade encrypted storage and access controls ensuring your health data remains private and secure.", f4_title: "Advanced Analytics", f4_desc: "Comprehensive health trend analysis with predictive modeling and personalized insights.", f5_title: "AI Assistant", f5_desc: "Intelligent chatbot powered by RAG technology to answer health questions and provide guidance.", f6_title: "Cloud Integration", f6_desc: "Seamless synchronization across all devices with real-time data backup and recovery." },
      dashboard: { title: "Real-Time Dashboard", subtitle: "Real-time IoT monitoring — Temperature · Oxygen · Humidity", temp: "Body Temperature", spO2: "Oxygen Saturation (SpO₂)", humidity: "Room Humidity", healthStatus: "AI Health Summary", aiInsight: "Smart AI Health Insights", aiInsightSub: "Powered by real-time sensor analysis", normal: "Normal", warning: "Warning", critical: "Critical", waiting: "Waiting for data...", chartTitle: "Live Sensor Readings over Time", noData: "No sensor data available yet.", welcome: "Welcome back", live: "Live", startLive: "Start Live", pause: "Pause", refreshAi: "Refresh AI", analyzing: "Analyzing...", logout: "Logout", lastUpdate: "Last updated:", emergency: "Emergency Alert", healthWarning: "Health Warning", avgTemp: "Avg Temp", avgO2: "Avg SpO₂", avgHumidity: "Avg Humidity", dataPoints: "Data Points", sensorReadings: "sensor readings", pulseOximeter: "Pulse Oximeter", noInsights: "No insights available right now." },
      appointments: { title: "Patient Appointments", subtitle: "View and manage upcoming visits using the same patient context as your dashboard.", selectPatient: "Select Patient", newPatient: "+ Create Patient Profile", upcoming: "Upcoming appointments", past: "Past appointments", nextAppointment: "Next appointment", scheduleBtn: "Schedule appointment", edit: "Edit", cancel: "Cancel", status: "Status", date: "Date & Time", reason: "Reason", scheduled: "scheduled", completed: "completed", cancelled: "cancelled", modalTitle: "Schedule Consultation", updateTitle: "Update Consultation", dateLabel: "Date & Time", durationLabel: "Duration (minutes)", reasonLabel: "Reason for visit", doctorLabel: "Doctor Name", typeLabel: "Consultation Type", typeGeneral: "General Checkup", typeFollowup: "Follow-up", typeSpecialist: "Specialist", cancelBtn: "Cancel", submitBtn: "Confirm Appointment", savingBtn: "Saving...", close: "Close", success: "Success!", savedMsg: "Appointment has been scheduled successfully.", updateSuccess: "Appointment updated successfully", deleteConfirm: "Are you sure you want to cancel this appointment?" },
      ocr: { title: "AI Medical OCR Scanner", subtitle: "Upload blood reports, prescriptions, or bills. Our AI instantly extracts key metrics, normal ranges, and flags abnormalities to help you understand your health.", dropzoneMain: "Upload Medical Report", dropzoneSub: "Drag & drop or click to browse", dropzoneDrop: "Drop your file here", maxSize: "Max 10 MB", analyzing: "Analyzing Document...", extractBtn: "Extract & Analyze", successTitle: "Analysis Complete", docType: "Document Type", summary: "Overall Summary", observations: "Key Observations", importantValues: "Important Values", abnormalities: "Possible Abnormalities", extractedText: "Raw Extracted Text", note: "This is an AI-generated summary. Please consult a doctor for medical advice.", uploadError: "Please upload an image or PDF first." },
      chatbot: { title: "HealthSync AI", subtitle: "Smart health assistant", placeholder: "Ask about your health...", defaultMsg: "Hello! 👋 I'm your HealthSync AI Assistant. I can help you understand health readings, appointments, OCR reports, and answer healthcare-related questions." },
      auth: { loginTitle: "Welcome Back", loginSub: "Sign in to your HealthSync account", emailLabel: "Email Address", emailPlaceholder: "you@example.com", passLabel: "Password", passPlaceholder: "Enter your password", signinBtn: "Sign In", signinginBtn: "Signing in...", noAccount: "Don't have an account?", createAccount: "Create account", demoNote: "Demo mode: any email & password will work if Supabase is not configured.", signupTitle: "Create Account", signupSub: "Join HealthSync today", nameLabel: "Full Name", namePlaceholder: "John Doe", signupBtn: "Create Account", signingupBtn: "Creating...", hasAccount: "Already have an account?", loginLink: "Sign in" },
      features: { title: "Powerful Features", subtitle: "Everything you need to monitor, analyze, and improve your health in one complete platform.", platformBadge: "Platform Features", coreFeatures: "Core Features", feat1: "Live Vitals", feat1Desc: "Monitor your SpO2, Heart Rate, and Temperature in real-time.", feat2: "AI Analysis", feat2Desc: "Get instant AI-powered insights from your medical reports.", feat3: "Smart Alerts", feat3Desc: "Receive immediate notifications for abnormal health readings.", feat4: "Secure Records", feat4Desc: "All your health data is encrypted and stored securely with HIPAA-aligned practices.", uptime: "Uptime Guarantee", monitoring: "Monitoring", dataProtection: "Data Protection" },
      howItWorks: { title: "How It Works", subtitle: "Start monitoring your health in three simple steps", desc: "Our end-to-end pipeline delivers continuous care through cutting-edge technology, from data collection to actionable insights.", step1: "Connect Device", step1Desc: "Pair your IoT sensor device securely.", step2: "Track Vitals", step2Desc: "View real-time charts and data.", step3: "Get Insights", step3Desc: "AI analyzes your trends for early warnings.", dataFlow: "Data Flow Pipeline", processOverview: "Complete Process Overview", techSpec: "Technical Specifications", step: "Step", stepOf: "of 5", s1_title: "Data Collection", s1_desc: "IoT sensors continuously capture Temperature, SpO₂, and Humidity with medical-grade precision.", s1_det: "Advanced sensors provide real-time monitoring with millisecond latency and 99.9% accuracy.", s2_title: "Edge Processing", s2_desc: "ESP32 microcontroller processes and encrypts data locally before secure transmission.", s2_det: "Local processing ensures data privacy and reduces bandwidth requirements while maintaining security.", s3_title: "Cloud AI Analysis", s3_desc: "Advanced AI models (CNN, LSTM, Transformer) analyze patterns and predict health trends.", s3_det: "Machine learning algorithms detect anomalies and provide early warning systems for potential health issues.", s4_title: "AI Assistant", s4_desc: "RAG-powered chatbot provides contextual insights and answers health-related questions.", s4_det: "Natural language processing makes complex medical data accessible through conversational AI.", s5_title: "Dashboard Visualization", s5_desc: "Real-time dashboard displays trends, alerts, and comprehensive health analytics.", s5_det: "Interactive charts and graphs help users understand their health patterns and make informed decisions.", techPrivacy: "Privacy-first", techPrivacyDesc: "Data Protection", techResponse: "<100ms", techResponseDesc: "Response Time", techAccuracy: "99.9%", techAccuracyDesc: "Accuracy Rate" },
      contact: { title: "Get in Touch", subtitle: "Have questions about HealthSync? We're here to help.", name: "Your Name", email: "Email Address", message: "Message", send: "Send Message", sending: "Sending..." },
      footer: { desc: "The next generation of smart healthcare monitoring.", links: "Quick Links", legal: "Legal", privacy: "Privacy Policy", terms: "Terms of Service", rights: "All rights reserved." }
    }
  },
  hi: {
    translation: {
      nav: { home: "होम", features: "विशेषताएं", howItWorks: "यह कैसे काम करता है", dashboard: "डैशबोर्ड", appointments: "अपॉइंटमेंट्स", ocrScanner: "OCR स्कैनर", contact: "संपर्क", logout: "लॉग आउट", hi: "नमस्ते" },
      hero: { badge: "लाइव हेल्थ मॉनिटरिंग", title1: "HealthSync", title2: "स्मार्ट हेल्थकेयर,", title3: "निर्बाध रूप से जुड़ा हुआ", subtitle: "वास्तविक समय में स्वास्थ्य की निगरानी करें, त्वरित AI स्वास्थ्य अंतर्दृष्टि प्राप्त करें, और अपनी स्वास्थ्य सेवा टीम से जुड़े रहें — कभी भी, कहीं भी।", startBtn: "निगरानी शुरू करें", aiBtn: "AI असिस्टेंट से बात करें", ocrBtn: "OCR स्कैन", feat1Title: "रीयल-टाइम मॉनिटरिंग", feat1Desc: "IoT-ग्रेड विश्वसनीयता और मिलीसेकंड विलंबता के साथ निरंतर तापमान, SpO₂ और आर्द्रता की निगरानी।", feat2Title: "AI इनसाइट्स", feat2Desc: "प्रारंभिक जोखिम का पता लगाने के लिए CNN, LSTM और ट्रांसफार्मर मॉडल द्वारा संचालित उन्नत भविष्य कहनेवाला विश्लेषण।", feat3Title: "सुरक्षित डैशबोर्ड", feat3Desc: "क्लाउड-सिंक स्वास्थ्य इतिहास, एन्क्रिप्टेड स्टोरेज, और मन की पूर्ण शांति के लिए व्यापक अलर्ट।", stat1: "अपटाइम", stat2: "निगरानी", stat3: "भविष्यवाणियां", stat4: "क्लाउड स्टोरेज" },
      home: { core: "मुख्य विशेषताएं", why: "HealthSync क्यों चुनें?", whyDesc: "हमारी अत्याधुनिक तकनीक के साथ स्वास्थ्य सेवा के भविष्य का अनुभव करें जो आपकी स्वास्थ्य निगरानी आपके हाथों में देती है।", moreFeat: "अधिक शक्तिशाली विशेषताएं", moreFeatDesc: "HealthSync को संपूर्ण स्वास्थ्य निगरानी समाधान बनाने वाली अतिरिक्त क्षमताओं की खोज करें।", ctaTitle: "क्या आप अपनी स्वास्थ्य निगरानी को बदलने के लिए तैयार हैं?", ctaDesc: "उन हजारों उपयोगकर्ताओं से जुड़ें जो अपनी स्वास्थ्य निगरानी आवश्यकताओं के लिए HealthSync पर भरोसा करते हैं।", ctaBtn1: "अभी शुरू करें", ctaBtn2: "और जानें", f1_title: "रीयल-टाइम वाइटल्स", f1_desc: "IoT-ग्रेड विश्वसनीयता और तत्काल स्वास्थ्य अंतर्दृष्टि के साथ निरंतर तापमान, ऑक्सीजन और आर्द्रता की निगरानी।", f2_title: "प्रेडिक्टिव AI", f2_desc: "उन्नत CNN, LSTM और ट्रांसफार्मर मॉडल जो जोखिम और रुझानों का जल्दी अनुमान लगाते हैं, सक्रिय स्वास्थ्य प्रबंधन प्रदान करते हैं।", f3_title: "सुरक्षित क्लाउड", f3_desc: "एंटरप्राइज़-ग्रेड एन्क्रिप्टेड स्टोरेज और एक्सेस नियंत्रण यह सुनिश्चित करते हैं कि आपका स्वास्थ्य डेटा निजी और सुरक्षित रहे।", f4_title: "उन्नत एनालिटिक्स", f4_desc: "भविष्य कहनेवाला मॉडलिंग और व्यक्तिगत अंतर्दृष्टि के साथ व्यापक स्वास्थ्य प्रवृत्ति विश्लेषण।", f5_title: "AI असिस्टेंट", f5_desc: "स्वास्थ्य संबंधी सवालों के जवाब देने और मार्गदर्शन प्रदान करने के लिए RAG तकनीक द्वारा संचालित बुद्धिमान चैटबॉट।", f6_title: "क्लाउड इंटीग्रेशन", f6_desc: "वास्तविक समय डेटा बैकअप और रिकवरी के साथ सभी उपकरणों में निर्बाध सिंक्रनाइज़ेशन।" },
      dashboard: { title: "रीयल-टाइम डैशबोर्ड", subtitle: "वास्तविक समय IoT निगरानी — तापमान · ऑक्सीजन · आर्द्रता", temp: "शरीर का तापमान", spO2: "ऑक्सीजन (SpO₂)", humidity: "आर्द्रता", healthStatus: "AI स्वास्थ्य सारांश", aiInsight: "स्मार्ट AI स्वास्थ्य अंतर्दृष्टि", aiInsightSub: "वास्तविक समय सेंसर विश्लेषण द्वारा संचालित", normal: "सामान्य", warning: "चेतावनी", critical: "गंभीर", waiting: "डेटा की प्रतीक्षा हो रही है...", chartTitle: "समय के साथ लाइव सेंसर रीडिंग", noData: "अभी तक कोई सेंसर डेटा उपलब्ध नहीं है।", welcome: "वापसी पर स्वागत है", live: "लाइव", startLive: "लाइव शुरू करें", pause: "रोकें", refreshAi: "AI रिफ्रेश करें", analyzing: "विश्लेषण हो रहा है...", logout: "लॉग आउट", lastUpdate: "अंतिम अपडेट:", emergency: "आपातकालीन चेतावनी", healthWarning: "स्वास्थ्य चेतावनी", avgTemp: "औसत तापमान", avgO2: "औसत SpO₂", avgHumidity: "औसत आर्द्रता", dataPoints: "डेटा पॉइंट्स", sensorReadings: "सेंसर रीडिंग", pulseOximeter: "पल्स ऑक्सीमीटर", noInsights: "अभी कोई अंतर्दृष्टि उपलब्ध नहीं है।" },
      appointments: { title: "मरीज के अपॉइंटमेंट्स", subtitle: "अपने डैशबोर्ड के समान रोगी संदर्भ का उपयोग करके आगामी यात्राओं को देखें और प्रबंधित करें।", selectPatient: "मरीज चुनें", newPatient: "+ मरीज प्रोफाइल बनाएं", upcoming: "आगामी अपॉइंटमेंट्स", past: "पिछले अपॉइंटमेंट्स", nextAppointment: "अगला अपॉइंटमेंट", scheduleBtn: "अपॉइंटमेंट तय करें", edit: "संपादित करें", cancel: "रद्द करें", status: "स्थिति", date: "तारीख और समय", reason: "कारण", scheduled: "निर्धारित", completed: "पूरा हुआ", cancelled: "रद्द", modalTitle: "परामर्श निर्धारित करें", updateTitle: "परामर्श अपडेट करें", dateLabel: "तारीख और समय", durationLabel: "अवधि (मिनट)", reasonLabel: "यात्रा का कारण", doctorLabel: "डॉक्टर का नाम", typeLabel: "परामर्श का प्रकार", typeGeneral: "सामान्य जांच", typeFollowup: "फॉलो-अप", typeSpecialist: "विशेषज्ञ", cancelBtn: "रद्द करें", submitBtn: "अपॉइंटमेंट की पुष्टि करें", savingBtn: "सहेजा जा रहा है...", close: "बंद करें", success: "सफल!", savedMsg: "अपॉइंटमेंट सफलतापूर्वक निर्धारित किया गया है।", updateSuccess: "अपॉइंटमेंट सफलतापूर्वक अपडेट किया गया", deleteConfirm: "क्या आप वाकई इस अपॉइंटमेंट को रद्द करना चाहते हैं?" },
      ocr: { title: "AI मेडिकल OCR स्कैनर", subtitle: "रक्त रिपोर्ट, नुस्खे या बिल अपलोड करें। हमारा AI आपके स्वास्थ्य को समझने में मदद करने के लिए तुरंत प्रमुख मीट्रिक निकालता है।", dropzoneMain: "मेडिकल रिपोर्ट अपलोड करें", dropzoneSub: "खींचें और छोड़ें या ब्राउज़ करने के लिए क्लिक करें", dropzoneDrop: "अपनी फ़ाइल यहाँ छोड़ें", maxSize: "अधिकतम 10 MB", analyzing: "दस्तावेज़ का विश्लेषण हो रहा है...", extractBtn: "निकालें और विश्लेषण करें", successTitle: "विश्लेषण पूर्ण", docType: "दस्तावेज़ का प्रकार", summary: "समग्र सारांश", observations: "मुख्य अवलोकन", importantValues: "महत्वपूर्ण मूल्य", abnormalities: "संभाव्य असामान्यताएं", extractedText: "निकाला गया टेक्स्ट", note: "यह AI जनित सारांश है। चिकित्सा सलाह के लिए डॉक्टर से परामर्श लें।", uploadError: "कृपया पहले एक छवि या पीडीएफ अपलोड करें।" },
      chatbot: { title: "HealthSync AI", subtitle: "स्मार्ट स्वास्थ्य सहायक", placeholder: "अपने स्वास्थ्य के बारे में पूछें...", defaultMsg: "नमस्ते! 👋 मैं आपका HealthSync AI असिस्टेंट हूँ। मैं आपको स्वास्थ्य रीडिंग, अपॉइंटमेंट, OCR रिपोर्ट समझने और स्वास्थ्य संबंधी सवालों के जवाब देने में मदद कर सकता हूँ।" },
      auth: { loginTitle: "वापसी पर स्वागत है", loginSub: "अपने HealthSync खाते में साइन इन करें", emailLabel: "ईमेल पता", emailPlaceholder: "you@example.com", passLabel: "पासवर्ड", passPlaceholder: "अपना पासवर्ड दर्ज करें", signinBtn: "साइन इन करें", signinginBtn: "साइन इन हो रहा है...", noAccount: "क्या आपके पास खाता नहीं है?", createAccount: "खाता बनाएं", demoNote: "डेमो मोड: कोई भी ईमेल और पासवर्ड काम करेगा यदि Supabase कॉन्फ़िगर नहीं है।", signupTitle: "खाता बनाएं", signupSub: "आज ही HealthSync से जुड़ें", nameLabel: "पूरा नाम", namePlaceholder: "John Doe", signupBtn: "खाता बनाएं", signingupBtn: "बनाया जा रहा है...", hasAccount: "क्या आपके पास पहले से खाता है?", loginLink: "साइन इन करें" },
      features: { title: "शक्तिशाली विशेषताएं", subtitle: "एक संपूर्ण प्लेटफ़ॉर्म में आपको अपने स्वास्थ्य की निगरानी, विश्लेषण और सुधार के लिए जो कुछ भी चाहिए।", platformBadge: "प्लेटफ़ॉर्म विशेषताएं", coreFeatures: "मुख्य विशेषताएं", feat1: "लाइव वाइटल्स", feat1Desc: "वास्तविक समय में अपने SpO2, हृदय गति और तापमान की निगरानी करें।", feat2: "AI विश्लेषण", feat2Desc: "अपनी मेडिकल रिपोर्ट से त्वरित AI अंतर्दृष्टि प्राप्त करें।", feat3: "स्मार्ट अलर्ट", feat3Desc: "असामान्य स्वास्थ्य रीडिंग के लिए तत्काल सूचनाएं प्राप्त करें।", feat4: "सुरक्षित रिकॉर्ड", feat4Desc: "आपका सभी स्वास्थ्य डेटा HIPAA-संरेखित प्रथाओं के साथ सुरक्षित रूप से एन्क्रिप्ट और संग्रहीत किया गया है।", uptime: "अपटाइम गारंटी", monitoring: "निगरानी", dataProtection: "डेटा सुरक्षा" },
      howItWorks: { title: "यह कैसे काम करता है", subtitle: "तीन सरल चरणों में अपने स्वास्थ्य की निगरानी शुरू करें", desc: "हमारी एंड-टू-एंड पाइपलाइन डेटा संग्रह से लेकर कार्रवाई योग्य अंतर्दृष्टि तक अत्याधुनिक तकनीक के माध्यम से निरंतर देखभाल प्रदान करती है।", step1: "डिवाइस कनेक्ट करें", step1Desc: "अपने IoT सेंसर डिवाइस को सुरक्षित रूप से पेयर करें।", step2: "वाइटल्स ट्रैक करें", step2Desc: "वास्तविक समय चार्ट और डेटा देखें।", step3: "अंतर्दृष्टि प्राप्त करें", step3Desc: "AI प्रारंभिक चेतावनियों के लिए आपके रुझानों का विश्लेषण करता है।", dataFlow: "डेटा प्रवाह पाइपलाइन", processOverview: "पूर्ण प्रक्रिया अवलोकन", techSpec: "तकनीकी विशिष्टताएं", step: "चरण", stepOf: "में से 5", s1_title: "डेटा संग्रह", s1_desc: "IoT सेंसर चिकित्सा-ग्रेड सटीकता के साथ तापमान, SpO₂ और आर्द्रता को लगातार कैप्चर करते हैं।", s1_det: "उन्नत सेंसर मिलीसेकंड विलंबता और 99.9% सटीकता के साथ वास्तविक समय निगरानी प्रदान करते हैं।", s2_title: "एज प्रोसेसिंग", s2_desc: "ESP32 माइक्रोकंट्रोलर सुरक्षित ट्रांसमिशन से पहले डेटा को स्थानीय रूप से प्रोसेस और एन्क्रिप्ट करता है।", s2_det: "स्थानीय प्रोसेसिंग डेटा गोपनीयता सुनिश्चित करती है और सुरक्षा बनाए रखते हुए बैंडविड्थ आवश्यकताओं को कम करती है।", s3_title: "क्लाउड AI विश्लेषण", s3_desc: "उन्नत AI मॉडल (CNN, LSTM, ट्रांसफार्मर) पैटर्न का विश्लेषण करते हैं और स्वास्थ्य प्रवृत्तियों की भविष्यवाणी करते हैं।", s3_det: "मशीन लर्निंग एल्गोरिदम विसंगतियों का पता लगाते हैं और संभावित स्वास्थ्य समस्याओं के लिए प्रारंभिक चेतावनी प्रणाली प्रदान करते हैं।", s4_title: "AI असिस्टेंट", s4_desc: "RAG-संचालित चैटबॉट प्रासंगिक अंतर्दृष्टि प्रदान करता है और स्वास्थ्य संबंधी प्रश्नों का उत्तर देता है।", s4_det: "प्राकृतिक भाषा प्रसंस्करण जटिल चिकित्सा डेटा को संवादात्मक AI के माध्यम से सुलभ बनाता है।", s5_title: "डैशबोर्ड विज़ुअलाइज़ेशन", s5_desc: "रीयल-टाइम डैशबोर्ड ट्रेंड, अलर्ट और व्यापक स्वास्थ्य विश्लेषण प्रदर्शित करता है।", s5_det: "इंटरएक्टिव चार्ट और ग्राफ उपयोगकर्ताओं को उनके स्वास्थ्य पैटर्न को समझने और सूचित निर्णय लेने में मदद करते हैं।", techPrivacy: "गोपनीयता-प्रथम", techPrivacyDesc: "डेटा सुरक्षा", techResponse: "<100ms", techResponseDesc: "प्रतिक्रिया समय", techAccuracy: "99.9%", techAccuracyDesc: "सटीकता दर" },
      contact: { title: "संपर्क करें", subtitle: "HealthSync के बारे में प्रश्न हैं? हम यहाँ मदद के लिए हैं।", name: "आपका नाम", email: "ईमेल पता", message: "संदेश", send: "संदेश भेजें", sending: "भेजा जा रहा है..." },
      footer: { desc: "स्मार्ट हेल्थकेयर मॉनिटरिंग की अगली पीढ़ी।", links: "त्वरित लिंक", legal: "कानूनी", privacy: "गोपनीयता नीति", terms: "सेवा की शर्तें", rights: "सर्वाधिकार सुरक्षित।" }
    }
  },
  mr: {
    translation: {
      nav: { home: "होम", features: "वैशिष्ट्ये", howItWorks: "हे कसे काम करते", dashboard: "डॅशबोर्ड", appointments: "अपॉइंटमेंट्स", ocrScanner: "OCR स्कॅनर", contact: "संपर्क", logout: "लॉग आउट", hi: "नमस्कार" },
      hero: { badge: "थेट आरोग्य निरीक्षण", title1: "HealthSync", title2: "स्मार्ट हेल्थकेअर,", title3: "अखंडपणे जोडलेले", subtitle: "रिअल-टाइममध्ये आरोग्यावर लक्ष ठेवा, त्वरित AI आरोग्य अंतर्दृष्टी मिळवा आणि आपल्या आरोग्य सेवा टीमशी कनेक्ट रहा — कधीही, कुठेही.", startBtn: "निरीक्षण सुरू करा", aiBtn: "AI असिस्टंटशी बोला", ocrBtn: "OCR स्कॅन", feat1Title: "रिअल-टाइम मॉनिटरिंग", feat1Desc: "IoT-ग्रेड विश्वासार्हता आणि मिलिसेकंद लेटेन्सीसह सतत तापमान, SpO₂ आणि आर्द्रता निरीक्षण.", feat2Title: "AI इनसाइट्स", feat2Desc: "लवकर धोका ओळखण्यासाठी CNN, LSTM आणि ट्रान्सफॉर्मर मॉडेल्सद्वारे समर्थित प्रगत भविष्यसूचक विश्लेषण.", feat3Title: "सुरक्षित डॅशबोर्ड", feat3Desc: "क्लाउड-सिंक केलेला आरोग्य इतिहास, एन्क्रिप्टेड स्टोरेज आणि संपूर्ण शांततेसाठी सर्वसमावेशक अलर्ट.", stat1: "अपटाइम", stat2: "निरीक्षण", stat3: "भविष्यवाणी", stat4: "क्लाउड स्टोरेज" },
      home: { core: "मुख्य वैशिष्ट्ये", why: "HealthSync का निवडावे?", whyDesc: "आमच्या अत्याधुनिक तंत्रज्ञानासह आरोग्य सेवेच्या भविष्याचा अनुभव घ्या जे तुमचे आरोग्य निरीक्षण तुमच्या हातात देते.", moreFeat: "अधिक शक्तिशाली वैशिष्ट्ये", moreFeatDesc: "HealthSync ला संपूर्ण आरोग्य निरीक्षण समाधान बनवणाऱ्या अतिरिक्त क्षमता शोधा.", ctaTitle: "तुम्ही तुमचे आरोग्य निरीक्षण बदलण्यास तयार आहात का?", ctaDesc: "त्या हजारो वापरकर्त्यांमध्ये सामील व्हा जे त्यांच्या आरोग्य निरीक्षणाच्या गरजांसाठी HealthSync वर विश्वास ठेवतात.", ctaBtn1: "आता सुरू करा", ctaBtn2: "अधिक जाणून घ्या", f1_title: "रिअल-टाइम वाइटल्स", f1_desc: "IoT-ग्रेड विश्वासार्हता आणि त्वरित आरोग्य अंतर्दृष्टीसह सतत तापमान, ऑक्सिजन आणि आर्द्रता निरीक्षण.", f2_title: "भविष्यसूचक AI", f2_desc: "प्रगत CNN, LSTM आणि ट्रान्सफॉर्मर मॉडेल्स जे जोखीम आणि ट्रेंडचा लवकर अंदाज लावतात, सक्रिय आरोग्य व्यवस्थापन प्रदान करतात.", f3_title: "सुरक्षित क्लाउड", f3_desc: "एंटरप्राइझ-ग्रेड एन्क्रिप्टेड स्टोरेज आणि ऍक्सेस कंट्रोल्स आपला आरोग्य डेटा खाजगी आणि सुरक्षित राहील याची खात्री करतात.", f4_title: "प्रगत विश्लेषण", f4_desc: "भविष्यसूचक मॉडेलिंग आणि वैयक्तिकृत अंतर्दृष्टीसह सर्वसमावेशक आरोग्य कल विश्लेषण.", f5_title: "AI सहाय्यक", f5_desc: "आरोग्याच्या प्रश्नांची उत्तरे देण्यासाठी आणि मार्गदर्शन प्रदान करण्यासाठी RAG तंत्रज्ञानाद्वारे समर्थित बुद्धिमान चॅटबॉट.", f6_title: "क्लाउड एकत्रीकरण", f6_desc: "रिअल-टाइम डेटा बॅकअप आणि रिकव्हरीसह सर्व उपकरणांवर अखंड सिंक्रोनाइझेशन." },
      dashboard: { title: "रिअल-टाइम डॅशबोर्ड", subtitle: "रिअल-टाइम IoT निरीक्षण — तापमान · ऑक्सिजन · आर्द्रता", temp: "शरीराचे तापमान", spO2: "ऑक्सिजन (SpO₂)", humidity: "आर्द्रता", healthStatus: "AI आरोग्य सारांश", aiInsight: "स्मार्ट AI आरोग्य अंतर्दृष्टी", aiInsightSub: "रिअल-टाइम सेन्सर विश्लेषणाद्वारे समर्थित", normal: "सामान्य", warning: "इशारा", critical: "गंभीर", waiting: "डेटाची प्रतीक्षा करत आहे...", chartTitle: "वेळेनुसार थेट सेन्सर रीडिंग", noData: "अद्याप कोणताही सेन्सर डेटा उपलब्ध नाही.", welcome: "परत आल्याबद्दल स्वागत आहे", live: "थेट", startLive: "थेट सुरू करा", pause: "थांबवा", refreshAi: "AI रिफ्रेश करा", analyzing: "विश्लेषण करत आहे...", logout: "लॉग आउट", lastUpdate: "अंतिम अपडेट:", emergency: "आणीबाणीचा इशारा", healthWarning: "आरोग्य इशारा", avgTemp: "सरासरी तापमान", avgO2: "सरासरी SpO₂", avgHumidity: "सरासरी आर्द्रता", dataPoints: "डेटा पॉइंट्स", sensorReadings: "सेन्सर रीडिंग", pulseOximeter: "पल्स ऑक्सिमीटर", noInsights: "सध्या कोणतीही अंतर्दृष्टी उपलब्ध नाही." },
      appointments: { title: "रुग्णाच्या अपॉइंटमेंट्स", subtitle: "तुमच्या डॅशबोर्डप्रमाणेच रुग्ण संदर्भाचा वापर करून आगामी भेटी पहा आणि व्यवस्थापित करा.", selectPatient: "रुग्ण निवडा", newPatient: "+ रुग्ण प्रोफाइल तयार करा", upcoming: "आगामी अपॉइंटमेंट्स", past: "मागील अपॉइंटमेंट्स", nextAppointment: "पुढील अपॉइंटमेंट", scheduleBtn: "अपॉइंटमेंट ठरवा", edit: "संपादित करा", cancel: "रद्द करा", status: "स्थिती", date: "तारीख आणि वेळ", reason: "कारण", scheduled: "नियोजित", completed: "पूर्ण झाले", cancelled: "रद्द", modalTitle: "सल्लामसलत ठरवा", updateTitle: "सल्लामसलत अपडेट करा", dateLabel: "तारीख आणि वेळ", durationLabel: "कालावधी (मिनिटे)", reasonLabel: "भेट देण्याचे कारण", doctorLabel: "डॉक्टरांचे नाव", typeLabel: "सल्लामसलतीचा प्रकार", typeGeneral: "सामान्य तपासणी", typeFollowup: "फॉलो-अप", typeSpecialist: "विशेषज्ञ", cancelBtn: "रद्द करा", submitBtn: "अपॉइंटमेंट निश्चित करा", savingBtn: "जतन करत आहे...", close: "बंद करा", success: "यशस्वी!", savedMsg: "अपॉइंटमेंट यशस्वीरित्या ठरवली आहे.", updateSuccess: "अपॉइंटमेंट यशस्वीरित्या अपडेट केली", deleteConfirm: "तुम्हाला खात्री आहे की तुम्हाला ही अपॉइंटमेंट रद्द करायची आहे?" },
      ocr: { title: "AI वैद्यकीय OCR स्कॅनर", subtitle: "रक्त अहवाल, प्रिस्क्रिप्शन किंवा बिल अपलोड करा. आमचे AI तुमचे आरोग्य समजून घेण्यासाठी त्वरित प्रमुख मेट्रिक्स काढते.", dropzoneMain: "वैद्यकीय अहवाल अपलोड करा", dropzoneSub: "ड्रॅग आणि ड्रॉप करा किंवा ब्राउझ करण्यासाठी क्लिक करा", dropzoneDrop: "तुमची फाईल येथे सोडा", maxSize: "कमाल 10 MB", analyzing: "दस्तऐवजाचे विश्लेषण करत आहे...", extractBtn: "काढा आणि विश्लेषण करा", successTitle: "विश्लेषण पूर्ण", docType: "दस्तऐवजाचा प्रकार", summary: "एकूण सारांश", observations: "मुख्य निरीक्षणे", importantValues: "महत्त्वाची मूल्ये", abnormalities: "संभाव्य विकृती", extractedText: "काढलेला मजकूर", note: "हा AI व्युत्पन्न केलेला सारांश आहे. वैद्यकीय सल्ल्यासाठी डॉक्टरांचा सल्ला घ्या.", uploadError: "कृपया प्रथम एक प्रतिमा किंवा PDF अपलोड करा." },
      chatbot: { title: "HealthSync AI", subtitle: "स्मार्ट आरोग्य सहाय्यक", placeholder: "तुमच्या आरोग्याबद्दल विचारा...", defaultMsg: "नमस्कार! 👋 मी तुमचा HealthSync AI सहाय्यक आहे. मी तुम्हाला आरोग्य वाचन, भेटी, OCR अहवाल समजून घेण्यात आणि आरोग्याशी संबंधित प्रश्नांची उत्तरे देण्यात मदत करू शकतो." },
      auth: { loginTitle: "परत आल्याबद्दल स्वागत आहे", loginSub: "तुमच्या HealthSync खात्यात साइन इन करा", emailLabel: "ईमेल पत्ता", emailPlaceholder: "you@example.com", passLabel: "पासवर्ड", passPlaceholder: "तुमचा पासवर्ड प्रविष्ट करा", signinBtn: "साइन इन करा", signinginBtn: "साइन इन करत आहे...", noAccount: "तुमचे खाते नाही का?", createAccount: "खाते तयार करा", demoNote: "डेमो मोड: जर Supabase कॉन्फिगर केलेले नसेल तर कोणताही ईमेल आणि पासवर्ड काम करेल.", signupTitle: "खाते तयार करा", signupSub: "आजच HealthSync मध्ये सामील व्हा", nameLabel: "पूर्ण नाव", namePlaceholder: "John Doe", signupBtn: "खाते तयार करा", signingupBtn: "तयार करत आहे...", hasAccount: "तुमचे आधीच खाते आहे का?", loginLink: "साइन इन करा" },
      features: { title: "शक्तिशाली वैशिष्ट्ये", subtitle: "एका संपूर्ण प्लॅटफॉर्मवर तुमचे आरोग्य निरीक्षण, विश्लेषण आणि सुधारण्यासाठी तुम्हाला आवश्यक असलेले सर्व काही.", platformBadge: "प्लॅटफॉर्म वैशिष्ट्ये", coreFeatures: "मुख्य वैशिष्ट्ये", feat1: "थेट वाइटल्स", feat1Desc: "रिअल-टाइममध्ये तुमच्या SpO2, हृदय गती आणि तापमानाचे निरीक्षण करा.", feat2: "AI विश्लेषण", feat2Desc: "तुमच्या वैद्यकीय अहवालांवरून त्वरित AI अंतर्दृष्टी मिळवा.", feat3: "स्मार्ट अलर्ट", feat3Desc: "असामान्य आरोग्य वाचनांसाठी त्वरित सूचना प्राप्त करा.", feat4: "सुरक्षित नोंदी", feat4Desc: "तुमचा सर्व आरोग्य डेटा HIPAA-अनुरूप पद्धतींनुसार एन्क्रिप्ट केलेला आणि सुरक्षितपणे संग्रहित केला आहे.", uptime: "अपटाइम हमी", monitoring: "निरीक्षण", dataProtection: "डेटा संरक्षण" },
      howItWorks: { title: "हे कसे काम करते", subtitle: "तीन सोप्या चरणांमध्ये तुमच्या आरोग्याचे निरीक्षण सुरू करा", desc: "आमची एंड-टू-एंड पाइपलाइन डेटा संकलनापासून ते कृती करण्यायोग्य अंतर्दृष्टीपर्यंत अत्याधुनिक तंत्रज्ञानाद्वारे सतत काळजी देते.", step1: "डिव्हाइस कनेक्ट करा", step1Desc: "तुमचे IoT सेन्सर डिव्हाइस सुरक्षितपणे पेअर करा.", step2: "वाइटल्स ट्रॅक करा", step2Desc: "रिअल-टाइम चार्ट आणि डेटा पहा.", step3: "अंतर्दृष्टी मिळवा", step3Desc: "लवकर इशाऱ्यांसाठी AI तुमच्या ट्रेंडचे विश्लेषण करते.", dataFlow: "डेटा प्रवाह पाइपलाइन", processOverview: "संपूर्ण प्रक्रिया आढावा", techSpec: "तांत्रिक वैशिष्ट्ये", step: "चरण", stepOf: "पैकी 5", s1_title: "डेटा संकलन", s1_desc: "IoT सेन्सर वैद्यकीय-दर्जाच्या अचूकतेसह तापमान, SpO₂ आणि आर्द्रता सतत कॅप्चर करतात.", s1_det: "प्रगत सेन्सर मिलिसेकंद लेटेन्सी आणि 99.9% अचूकतेसह रिअल-टाइम निरीक्षण प्रदान करतात.", s2_title: "एज प्रोसेसिंग", s2_desc: "ESP32 मायक्रोकंट्रोलर सुरक्षित ट्रांसमिशनपूर्वी डेटा स्थानिक पातळीवर प्रक्रिया करतो आणि एन्क्रिप्ट करतो.", s2_det: "स्थानिक प्रक्रिया डेटा गोपनीयता सुनिश्चित करते आणि सुरक्षा राखत बँडविड्थ आवश्यकता कमी करते.", s3_title: "क्लाउड AI विश्लेषण", s3_desc: "प्रगत AI मॉडेल्स (CNN, LSTM, ट्रान्सफॉर्मर) नमुने विश्लेषण करतात आणि आरोग्य ट्रेंडची भविष्यवाणी करतात.", s3_det: "मशीन लर्निंग अल्गोरिदम विसंगती शोधतात आणि संभाव्य आरोग्य समस्यांसाठी प्रारंभिक चेतावणी प्रणाली प्रदान करतात.", s4_title: "AI असिस्टंट", s4_desc: "RAG-समर्थित चॅटबॉट प्रासंगिक अंतर्दृष्टी प्रदान करतो आणि आरोग्य संबंधित प्रश्नांची उत्तरे देतो.", s4_det: "नैसर्गिक भाषा प्रक्रिया संवादात्मक AI द्वारे जटिल वैद्यकीय डेटा सुलभ बनवते.", s5_title: "डॅशबोर्ड व्हिज्युअलायझेशन", s5_desc: "रिअल-टाइम डॅशबोर्ड ट्रेंड, अलर्ट आणि सर्वसमावेशक आरोग्य विश्लेषण प्रदर्शित करतो.", s5_det: "इंटरएक्टिव्ह चार्ट आणि आलेख वापरकर्त्यांना त्यांचे आरोग्य नमुने समजून घेण्यास आणि माहितीपूर्ण निर्णय घेण्यास मदत करतात.", techPrivacy: "गोपनीयता-प्रथम", techPrivacyDesc: "डेटा संरक्षण", techResponse: "<100ms", techResponseDesc: "प्रतिसाद वेळ", techAccuracy: "99.9%", techAccuracyDesc: "अचूकता दर" },
      contact: { title: "संपर्क साधा", subtitle: "HealthSync बद्दल प्रश्न आहेत? आम्ही मदतीसाठी येथे आहोत.", name: "तुमचे नाव", email: "ईमेल पत्ता", message: "संदेश", send: "संदेश पाठवा", sending: "पाठवत आहे..." },
      footer: { desc: "स्मार्ट हेल्थकेअर मॉनिटरिंगची पुढची पिढी.", links: "क्विक लिंक्स", legal: "कायदेशीर", privacy: "गोपनीयता धोरण", terms: "सेवा अटी", rights: "सर्व हक्क राखीव." }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false 
    }
  });

export default i18n;
